docker_user:
docker_password:
docker_login_url:
registry: '{{ docker_login_url }}/some-docker-path'
image_prefixes: 'some-image-prefix,some-image-prefix2' # NO SPACES
image_postfix: image-postfix
image_tag: 1.0

image_prefix_list: "{{ image_prefixes.split(',') }}"
