- name: Check if already installed.
  become: true
  become_flags: -H
  shell: "docker --version"
  register: docker_version_check
  ignore_errors: true

- name: If installation doesn't already exist, install now.
  when: docker_version_check.rc != 0
  become: true
  block:
    - name: Add Docker's GPG key
      apt_key:
        url: '{{ docker_gpg_key_url }}'
        state: present

    - name: Add the Docker (stable) repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
